# Generated by Django 3.2.7 on 2022-04-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
    ]
