# Generated by Django 3.2.7 on 2022-04-29 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20220408_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.diagnostic'),
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.diagnostic')),
            ],
        ),
    ]
