# Generated by Django 3.2.7 on 2022-05-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
