# Generated by Django 3.2.7 on 2022-05-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosticresult',
            old_name='mark',
            new_name='mark1',
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='mark2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='mark3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='mark4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='mark1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mark2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mark3',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='mark4',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
