# Generated by Django 3.2.7 on 2022-05-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220530_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='ans',
        ),
    ]
