# Generated by Django 3.2.7 on 2022-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_title_answer_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Methodist2Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.ManyToManyField(to='core.Methodist2Teacher')),
            ],
        ),
    ]
