# Generated by Django 3.2.7 on 2022-05-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_methodist2teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Methodist2Teacher',
        ),
    ]
