# Generated by Django 3.2.7 on 2022-05-31 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_methodist2teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodistLessonSigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('lesson_title', models.CharField(blank=True, max_length=256, null=True)),
                ('lesson_description', models.TextField(blank=True, null=True)),
                ('lesson_plan', models.FileField(upload_to='files')),
                ('methodist_comment', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
