# Generated by Django 3.2.7 on 2022-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_methodistlessonsigns'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodistlessonsigns',
            name='status',
            field=models.CharField(choices=[('ОТКЛ', 'Отклонено'), ('СМОТР', 'На рассмотрении'), ('ОДОБР', 'Одобрено'), ('ОТКАЗ', 'Отказ участника'), ('ПРОВ', 'Проведено')], default='СМОТР', max_length=32),
        ),
    ]
