# Generated by Django 3.2.7 on 2022-06-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_methodmanual'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MethodManual',
            new_name='RouteManual',
        ),
    ]
