# Generated by Django 3.2.7 on 2022-06-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='weight',
            new_name='order',
        ),
    ]
