# Generated by Django 3.2.7 on 2022-06-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_weight_route_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemanual',
            name='author',
        ),
        migrations.AddField(
            model_name='routemanual',
            name='type',
            field=models.CharField(choices=[('КПК', 'Курс повышения квалификации'), ('СЕМ', 'Семинар'), ('МЕТ', 'Методичка')], default='КПК', max_length=32),
        ),
        migrations.AlterField(
            model_name='route',
            name='order',
            field=models.IntegerField(default=1000),
        ),
    ]
