# Generated by Django 3.2.7 on 2022-06-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220606_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('АКТИВ', 'В процессе'), ('ЗАКР', 'Завершен'), ('ПЛАН', 'Запланирован')], default='ПЛАН', max_length=32),
        ),
    ]
