# Generated by Django 3.2.7 on 2022-06-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_route_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='reflection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
