# Generated by Django 3.2.7 on 2022-06-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_eventeditedfield_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEditedFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(blank=True, max_length=256, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.events')),
            ],
        ),
        migrations.DeleteModel(
            name='EventEditedField',
        ),
    ]
