# Generated by Django 3.2.7 on 2022-06-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20220621_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventeditedfields',
            old_name='event_id',
            new_name='event',
        ),
    ]
