# Generated by Django 3.2.7 on 2022-06-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220622_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventeditedfields',
            old_name='c_state',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='eventeditedfields',
            old_name='prev_state',
            new_name='prev',
        ),
    ]
