# Generated by Django 3.2.7 on 2022-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220622_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodistlessonsigns',
            name='meet_link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='methodistlessonsigns',
            name='meet_type',
            field=models.CharField(choices=[('ДИСТ', 'Дистанционная встреча'), ('ОЧНО', 'Очная встреча')], default='ОЧНО', max_length=32),
        ),
        migrations.AlterField(
            model_name='methodistlessonsigns',
            name='status',
            field=models.CharField(choices=[('ОТКЛ', 'Отклонено'), ('СМОТР', 'На рассмотрении'), ('СОГЛОФ', 'Согласована очная встреча'), ('СОГЛОН', 'Согласована дистанционная встреча'), ('ОТКАЗ', 'Отказ участника'), ('ПРОВ', 'Проведено')], default='СМОТР', max_length=32),
        ),
    ]
