# Generated by Django 3.2.7 on 2022-06-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220628_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('АКТИВ', 'В процессе'), ('ЗАКР', 'Завершен')], default='ПЛАН', max_length=32),
        ),
    ]
