# Generated by Django 3.2.8 on 2022-09-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_methodmunicipality_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question'),
        ),
        migrations.AlterField(
            model_name='diagnosticresult',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosticresult',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnostic'),
        ),
        migrations.AlterField(
            model_name='methodist2teacher',
            name='methodist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methodist2teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='methodist2teacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='methodistlessonsigns',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnostic'),
        ),
        migrations.AlterField(
            model_name='route',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='manual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.routemanual'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='mark1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Методические компетенции'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='mark2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Функциональная грамотность'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='mark3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Психолого-педагогические компетенции'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='mark4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Предметные компетенции'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='routemanual',
            name='type',
            field=models.CharField(choices=[('КПК', 'Курс повышения квалификации'), ('СЕМ', 'Семинар'), ('МЕТ', 'Методичка')], default='КПК', max_length=32, verbose_name='Тип'),
        ),
    ]
