# Generated by Django 3.2.8 on 2022-09-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
