# Generated by Django 3.2.8 on 2022-09-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_diagnostic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='reflection',
        ),
        migrations.CreateModel(
            name='RouteReflection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('РАССМ', 'На рассмотрении'), ('ПОДТВ', 'Подтвержден'), ('ОТКЛ', 'Отклонено')], default='РАССМ', max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
    ]
