# Generated by Django 3.2.8 on 2022-09-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220912_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routereflection',
            old_name='reason',
            new_name='commentary',
        ),
    ]
