# Generated by Django 3.2.8 on 2022-09-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220913_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventeditedfields',
            name='current',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventeditedfields',
            name='fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventeditedfields',
            name='prev',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
