# Generated by Django 3.2.8 on 2022-09-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonsigns',
            name='status',
            field=models.CharField(choices=[('ОТКЛ', 'Отклонено'), ('СМОТР', 'На рассмотрении'), ('СОГЛ', 'Согласована'), ('ОТКАЗ', 'Отказ участника'), ('ПРОВ', 'Проведено')], default='СМОТР', max_length=32),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('АКТИВ', 'В процессе'), ('ЗАКР', 'Завершен')], default='АКТИВ', max_length=32),
        ),
        migrations.AlterField(
            model_name='routereflection',
            name='status',
            field=models.CharField(choices=[('СМОТР', 'На рассмотрении'), ('ПОДТВ', 'Подтвержден'), ('ОТКЛ', 'Отклонено')], default='РАССМ', max_length=32),
        ),
    ]
