# Generated by Django 3.2.7 on 2021-09-23 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210922_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='moderator',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='admin',
            new_name='superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='full_name',
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='account',
            name='education_class',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='account',
            name='education_organization',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='middle_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='municipality',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
