# Generated by Django 3.2.7 on 2021-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210924_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_organization',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='municipality',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
