# Generated by Django 3.2.7 on 2021-11-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
