# Generated by Django 3.2.7 on 2022-01-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='region',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='national',
            field=models.CharField(blank=True, choices=[('ПР', 'Прочее'), ('РФ', 'Российская федерация')], max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='subject_of_country',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
