# Generated by Django 3.2.7 on 2022-01-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='education_rank',
            field=models.CharField(blank=True, choices=[('Н', 'Нет звания'), ('КН', 'Доцент'), ('ДОК', 'Профессор')], max_length=32),
        ),
    ]
