# Generated by Django 3.2.7 on 2022-07-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_methodmunicipality_municipality'),
        ('accounts', '0017_account_methodist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subject_of_country',
        ),
        migrations.AlterField(
            model_name='account',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
    ]
