# Generated by Django 3.2.7 on 2022-07-05 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_methodmunicipality_municipality'),
        ('accounts', '0018_auto_20220705_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
    ]
