# Generated by Django 3.2.7 on 2022-07-06 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_methodmunicipality_municipality'),
        ('accounts', '0021_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='education_level',
            field=models.CharField(choices=[('ПР', 'Прочее'), ('СПО', 'СПО'), ('БКВТ', 'Бакалавриат'), ('СПЦ', 'Специалитет'), ('МАГ', 'Магистратура')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_pow',
            field=models.CharField(choices=[('Н', 'Нет степени'), ('КН', 'Кандидат наук'), ('ДОК', 'Доктор наук')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_rank',
            field=models.CharField(choices=[('Н', 'Нет звания'), ('КН', 'Доцент'), ('ДОК', 'Профессор')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='municipality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
        migrations.AlterField(
            model_name='account',
            name='national',
            field=models.CharField(choices=[('ПР', 'Прочее'), ('РФ', 'Российская федерация')], default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='work_edu_exp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='work_exp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
