# Generated by Django 3.2.7 on 2022-07-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20220706_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='education_level',
            field=models.CharField(choices=[('ПР', 'Прочее'), ('СПО', 'СПО'), ('БКВТ', 'Бакалавриат'), ('СПЦ', 'Специалитет'), ('МАГ', 'Магистратура')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_pow',
            field=models.CharField(choices=[('Н', 'Нет степени'), ('КН', 'Кандидат наук'), ('ДОК', 'Доктор наук')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_rank',
            field=models.CharField(choices=[('Н', 'Нет звания'), ('КН', 'Доцент'), ('ДОК', 'Профессор')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='national',
            field=models.CharField(choices=[('ПР', 'Прочее'), ('РФ', 'Российская федерация')], default=None, max_length=32, null=True),
        ),
    ]
