# Generated by Django 3.2.8 on 2022-09-15 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220707_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='document_department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='document_place_birth',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_document_first_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_document_middle_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_document_second_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_level',
            field=models.CharField(choices=[('ПР', 'Прочее'), ('СПО', 'СПО'), ('БКВТ', 'Бакалавриат'), ('СПЦ', 'Специалитет'), ('МАГ', 'Магистратура')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_pow',
            field=models.CharField(choices=[('Н', 'Нет степени'), ('КН', 'Кандидат наук'), ('ДОК', 'Доктор наук')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_qualify',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='account',
            name='education_rank',
            field=models.CharField(choices=[('Н', 'Нет звания'), ('КН', 'Доцент'), ('ДОК', 'Профессор')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='account',
            name='national',
            field=models.CharField(choices=[('ПР', 'Прочее'), ('РФ', 'Российская федерация')], default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='work',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='work_pos',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
