from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('moderate/courses', views.ModerateCoursesListView.as_view(), name='moderate-courses'),
    path('moderate/profiles', views.ModerateProfilesListView.as_view(), name='moderate-profiles'),
    path('moderate/profiles/<int:pk>', views.ModerateAccountView.as_view(), name='moderate-profile-card'),
    path('moderate/manuals', views.ModerateManualsListView.as_view(), name='moderate-manuals'),
    path('moderate/manuals/create', views.ModerateManualsCreateView.as_view(), name='moderate-manuals-create'),
    path('moderate/manuals/<int:pk>/delete', views.ModerateManualsDeleteView.as_view(), name='moderate-manuals-delete'),
    path('moderate/manuals/<int:pk>/update', views.ModerateManualsUpdateView.as_view(), name='moderate-manuals-update'),
    path('moderate/courses/<int:pk>/signs', views.AccountCourseListView.as_view(), name='moderate-courses-signs-view'),
    path('moderate/methodist', views.ModerateMethodistFormView.as_view(), name='moderate-methodist'),
    path('moderate/diagnostics', views.ModerateDiagnosticsListView.as_view(), name='moderate-diagnostics'),
    path('moderate/diagnostics/create', views.ModerateDiagnosticsCreateView.as_view(), name='moderate-diagnostics-create'),
    path('moderate/diagnostics/<int:pk>/update', views.ModerateDiagnosticsUpdateView.as_view(), name='moderate-diagnostics-update'),
    path('moderate/diagnostics/<int:pk>/delete', views.ModerateDiagnosticsDeleteView.as_view(), name='moderate-diagnostics-delete'),
    path('route', views.RouteView.as_view(), name='route'),
    path('route/manuals', views.RouteManualsListView.as_view(), name='route-manuals'),
    path('route/manuals/<int:pk>/add', views.add2route_manual, name='route-add'),
    path('route/manuals/<int:pk>/delete', views.RouteDeleteView.as_view(), name='route-delete'),
    path('route/manuals/<int:pk>/update', views.RouteUpdateView.as_view(), name='route-update'),
    path('route/diagnostics', views.DiagnosticListView.as_view(), name='route-diagnostics'),
    path('route/diagnostics/<int:pk>', views.DiagnosticDetailView.as_view(), name='route-diagnostics-item'),
    path('route/diagnostics/result/<int:pk>', views.DiagnosticResultView.as_view(), name='route-diagnostics-result'),
    path('route/signs/create', views.RouteSignsCreateView.as_view(), name='route-signs-create'),
    path('route/signs/<int:pk>', views.RouteSignsUpdateView.as_view(), name='route-signs-update'),
    path('route/<int:pk>/reflection/create', views.RouteReflectionCreateView.as_view(), name='route-reflection-create'),
    path('route/reflection/<int:pk>/update', views.RouteReflectionUpdateView.as_view(), name='route-reflection-update'),
    path('method/profiles', views.MethodProfilesListView.as_view(), name='method-profiles'),
    path('method/signs', views.MethodSignsListView.as_view(), name='method-signs'),
    path('method/signs/<int:pk>', views.MethodSignsUpdateView.as_view(), name='method-signs-update'),
    path('method/profiles/<int:pk>', views.MethodProfilesDetailView.as_view(), name='method-profiles-item'),
    path('method/reflections/<int:pk>', views.MethodReflectionUpdateView.as_view(), name='method-reflections-update'),
    path('method', views.MethodView.as_view(), name='method'),
]