# Generated by Django 3.2.8 on 2022-09-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('mark1', models.BooleanField(blank=True, default=False)),
                ('mark2', models.BooleanField(blank=True, default=False)),
                ('mark3', models.BooleanField(blank=True, default=False)),
                ('mark4', models.BooleanField(blank=True, default=False)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.IntegerField(blank=True, null=True)),
                ('mark2', models.IntegerField(blank=True, null=True)),
                ('mark3', models.IntegerField(blank=True, null=True)),
                ('mark4', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.diagnostic')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('correct', models.BooleanField(blank=True, default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostics.question')),
            ],
        ),
    ]
