# Generated by Django 3.2.7 on 2021-10-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcourse',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='accountcourse',
            old_name='course_id',
            new_name='course',
        ),
    ]
