# Generated by Django 3.2.7 on 2021-10-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20211004_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='course',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='accountcourse',
            name='role',
            field=models.CharField(default='Участник', max_length=64),
        ),
    ]
