# Generated by Django 3.2.7 on 2021-10-06 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211006_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcourse',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 6, 7, 48, 18, 555646, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
