# Generated by Django 3.2.7 on 2021-10-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_accountcourse_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='accountcourse',
            name='role',
            field=models.CharField(choices=[('УЧ', 'Участник'), ('ЭКСП', 'Эксперт'), ('КООРД', 'Координатор')], default='УЧ', max_length=32),
        ),
        migrations.AlterField(
            model_name='accountcourse',
            name='status',
            field=models.CharField(choices=[('ОТКЛ', 'Отклонено'), ('СМОТР', 'На рассмотрении'), ('ОДОБР', 'Одобрено'), ('ОТКАЗ', 'Отказ участника')], default='СМОТР', max_length=32),
        ),
    ]
