# Generated by Django 3.2.7 on 2021-11-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20211006_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
