# Generated by Django 3.2.7 on 2022-01-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_accountcourse_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description_url',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='program_goal',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(blank=True, choices=[('КПК', 'Курс повышения квалификации'), ('СЕМ', 'Семинар')], max_length=64),
        ),
    ]
