# Generated by Django 3.2.7 on 2022-02-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_programcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
