# Generated by Django 3.2.7 on 2022-02-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
