# Generated by Django 3.2.7 on 2022-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20220210_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=models.CharField(default='all', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='all', max_length=256),
        ),
    ]
