# Generated by Django 3.2.7 on 2022-02-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20220210_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramCourse',
            new_name='CourseProgram',
        ),
        migrations.CreateModel(
            name='CourseSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
