# Generated by Django 3.2.7 on 2022-02-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20220210_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursespeakers',
            old_name='speaker',
            new_name='name',
        ),
    ]
