# Generated by Django 3.2.8 on 2022-09-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20220812_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='profile',
            field=models.CharField(choices=[('ВСЕ', 'Все профили'), ('Предметные', 'Предметные'), ('Метапредметные', 'Метапредметные'), ('Управленческие', 'Управленческие')], default='ВСЕ', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('ВСЕ', 'Все предметы'), ('Биология', 'Биология'), ('Математика', 'Математика')], default='ВСЕ', max_length=256),
        ),
        migrations.AlterField(
            model_name='courseprogram',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
