# Generated by Django 3.2.8 on 2022-09-13 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_auto_20220909_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountCourse',
            new_name='Account2Course',
        ),
    ]
